defaults: &DEFAULTS
  metadata_engine: StashDatacite
  shared_resource_model: StashEngine::Resource
  repository: Stash::Merritt::Repository
  stash_mount: /stash
  max_review_days: 180
  ezid:
    host: ezid.cdlib.org
    port: 443
  google_maps_api_key: <add_key_here>


development: &DEVELOPMENT
  <<: *DEFAULTS
  shib_sp_host: <where-to-find-shibboleth-service-provider>
  google_client_id: <google-client-id>
  google_client_secret: <google-client-secret>
  # sandbox orcid credentials
  site: https://sandbox.orcid.org/
  authorize_url: https://sandbox.orcid.org/oauth/authorize
  token_url: https://api.sandbox.orcid.org/oauth/token
  orcid_key:  <orcid-key>
  orcid_secret: <orcid-secret>
  member: true
  sandbox: true
  page_error_email: [someemail@example.org, someotheremail@example.org]
  submission_error_email: [someemail@example.org]
  feedback_email_from: no-reply-dryad-dev@datadryad.org
  collection_uri: http://someserver.example.org:39001/mrtsword/
  contact_us_uri: http://some.example.org/services/uc3/contact.html
  google_analytics_id: <some-google-analytics-id>

local:
  <<: *DEVELOPMENT

test:
  <<: *DEFAULTS
