default: &default
  adapter: mysql2
  database: dryad
  password: blank
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development: &DEVELOPMENT
  <<: *default
  host: 127.0.0.1 # change these lines or override lines from default if they are not right
  username: root
  password: ""

local:
  <<: *DEVELOPMENT

test:
  <<: *default
  database: dashv2_test
  username: travis
