default: &default
  adapter: mysql2
  database: dash
  password: blank
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  host: 127.0.0.1 # change these lines or override lines from default if they are not right
  username: root
  password: ""

test:
  <<: *default
  host: 127.0.0.1 # change these lines or override lines from default if they are not right
  username: travis
  password: ""

stage:
  <<: *default
  host: my.stage.db.server # change these lines or override lines from default if they are not right
  username: my_stage_username
  password: "my_stage_password"

production:
  <<: *default
  host: my.production.db.server # change these lines or override lines from default if they are not right
  username: my_production_username
  password: "my_production_password"

# for a short explanation of default and inheritance, see the app_config.yml file
