# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d5a86c53287b8f3f53c3eef3c1d79edd6683e79448dd54c9b37b979b0901e9743cb0a663ab9f6440ca4f1a200741d091711f5dd77bd5ff306ce649b9b077a4
  # change secret keys such as above.  You can generate a new one with "bundle exec rake secret"

stage:
  secret_key_base: 4e29d63096512ce9d1edb914c524d76f1a897782b2ac8e48ba5c0e2f4d8db44c07dbc9ccaf42218c614991beaf59b224064350829028c9bea21bcd37ab0eb2eb
  # change secret keys such as above.  You can generate a new one with "bundle exec rake secret"

test:
  secret_key_base: 842603b0509f9296db42b864d009d4866f5a52b3dddc9f930ffc1474148337773735462742f2ea6c460cbbf3f9230e07408eeebbc4e4d42e8596344f40eba621
  # change secret keys such as above.  You can generate a new one with "bundle exec rake secret"

production:
  secret_key_base: 63079d70a8d63302380a6bc5e37a301ddf0cadff98cfb56397393b37872115aed81756486f6f05cb4ac5259d549f3638e63190fab004e3f36fa6a70129ca9667
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> # if you'd like to read it from the environment instead
  # change secret keys such as above.  You can generate a new one with "bundle exec rake secret"
